### ISSUE TITLE
Preventing `arbitrary` being re-exported

### ISSUE THREAD

**Issue by yatesco** [matklad/arbtest#5]
Hi - is there a reason `arbtest::arbitrary` is publicly re-exported? I keep running into an issue where my IDE produces`use arbtest::arbitrary::{Self, Unstructured}` instead of `use arbitrary::Unstructured`. I tried to work around this by fully qualifying the `#[derive(arbitrary::Arbitrary)]` but it just pulls in `use arbtest::arbitrary::Self`.

Is the intention for me to *only* depend on `arbtest` as oppose to both `arbtest` and `arbitrary`? At the moment I'm pulling in `arbitrary` as a dependency as well.

Thanks! (It's entirely possible I'm doing something dumb...)

**Comment by matklad** [comment]
Yes, this is intentional! arbitrary is a public dependency, so re-exporting
both frees the user from the need to add a second line to cargo.toml, and
also makes sure that the right version of arbitrary is used. Though, I must
say I am not entirely sure whether that works with derive, it might require
having a direct dependency on the crate…

**Comment by yatesco** [comment]
thanks @matklad - I'll see if `derive` works with depending only on the `arbtest` crate and comment back on this thread.

Thanks again for you many, many contributions to the rust eco-system. Without your work on IntelliJ and rust-analyzer I don't think Rust would be as popular and accessible as it is today.

**Comment by yatesco** [comment]
Yes, it works fine. I've created an example in https://github.com/yatesco/arbtest-derive-example which has two crates, both of which depend only on `arbtest` and one which uses the `derive`d `Arbitrary` implementations from the other crate.

Thanks!

**Comment by yatesco** [comment]
NOTE: `#[cfg_attr(any(feature = "tests", test) derive(arbtest::arbitrary::Arbitrary))]` doesn't work. Instead, use:
```rust
#[cfg(any(feature = "tests", test)))]
use arbtest::arbitrary;

#[cfg_attr(any(feature = "tests",test) derive(arbitrary::Arbitrary))]
struct A {}
```
